derivation_of_non-linear_equilibrium:
	pdflatex derivation_of_non-linear_equilibrium.tex
	pdflatex derivation_of_non-linear_equilibrium.tex

linear_equilibrium_solutions:
	pdflatex linear_equilibrium_solutions.tex
	pdflatex linear_equilibrium_solutions.tex

SIMULATION:
	pdflatex SIMULATION.tex
	pdflatex SIMULATION.tex

stability_of_non-linear_equilibrium:
	pdflatex stability_of_non-linear_equilibrium.tex
	pdflatex stability_of_non-linear_equilibrium.tex

two_self-coupled_and_inter-coupled_daughters:
	pdflatex two_self-coupled_and_inter-coupled_daughters.tex
	pdflatex two_self-coupled_and_inter-coupled_daughters.tex

expected_energy_dissipation_rates:
	pdflatex expected_energy_dissipation_rates.tex
	pdflatex expected_energy_dissipation_rates.tex

N_inter-coupled_daughters:
	pdflatex N_inter-coupled_daughters.tex
	pdflatex N_inter-coupled_daughters.tex

single_self-coupled_daughter:
	pdflatex single_self-coupled_daughter.tex
	pdflatex single_self-coupled_daughter.tex

summary_of_non-linear_equilibrium_solution:
	pdflatex summary_of_non-linear_equilibrium_solution.tex
	pdflatex summary_of_non-linear_equilibrium_solution.tex

limitting_cases_of_non-linear_equilibrium:
	pdflatex limitting_cases_of_non-linear_equilibrium.tex
	pdflatex limitting_cases_of_non-linear_equilibrium.tex

preliminaries:
	pdflatex preliminaries.tex
	pdflatex preliminaries.tex

stability_of_linear_equilibrium_solutions:
	pdflatex stability_of_linear_equilibrium_solutions.tex
	pdflatex stability_of_linear_equilibrium_solutions.tex

two_pairs_of_daughters:
	pdflatex two_pairs_of_daughters.tex
	pdflatex two_pairs_of_daughters.tex

